#!/usr/bin/env python

# Client for submitting feature files to the Acousticbrainz project

# Copyright 2014 Music Technology Group - Universitat Pompeu Fabra
# acousticbrainz-client is available under the terms of the GNU
# General Public License, version 3 or higher. See COPYING for more details.

import argparse
from abz import acousticbrainz

def main(paths):
    acousticbrainz.load_processed_filelist()
    for path in paths:
        acousticbrainz.process(path)

if __name__ == "__main__":
    p = argparse.ArgumentParser(description="Acousticbrainz client")
    p.add_argument("p", help="Path to upload", nargs='*')

    args = p.parse_args()
    if args.p:
        main(args.p)
    else:
        p.print_usage()
