#!/usr/bin/env python

import argparse
from abz import acousticbrainz

def main(paths):
    acousticbrainz.load_processed_filelist()
    for path in paths:
        acousticbrainz.process(path)

if __name__ == "__main__":
    p = argparse.ArgumentParser(description="Acousticbrainz client")
    p.add_argument("p", help="Path to upload", nargs='*')

    args = p.parse_args()
    if args.p:
        main(args.p)
    else:
        p.print_usage()
