#!/usr/bin/env python
from __future__ import print_function
from flask import Flask
import time
import random

# Set to True to randomly return an error from the server
FAIL_SUBMIT = False

app = Flask(__name__)


@app.route("/<mbid>/low-level", methods=["POST"])
def submit_low_level(mbid):
    print("Submission for mbid: %s" % mbid)
    if FAIL_SUBMIT and random.random() > 0.9:
        print("Randomly decided to return a failure")
        return "error", 400
    time.sleep(1)
    return "thank you for your submission"

if __name__ == "__main__":
    app.run(debug=True, host="127.0.0.1", port=8080)
