#!/usr/bin/env python
from flask import Flask

app = Flask(__name__)

@app.route("/<mbid>/low-level", methods=["POST"])
def submit_low_level(mbid):
    print "Submission for mbid", mbid
    return ""

if __name__ == "__main__":
    app.run(debug=True, host="127.0.0.1", port=8989)
